# ***************************通用配置: 请不要修改此文件，此文件由模板自动生成，若要修改，请移步至conftpl目录**************************** #
# 应用版本
version: 0.15.0.0
#服务器配置
server:
  servlet:
    context-path: /browser-server
#Spring应用配置
spring:
  profiles.active: test
  application.name: browser-api
  session.timeout: 1800  #以秒为单位
  #国际化配置
  messages.basename: messages
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  #Redis集群配置
  redis:
    database: 0
    key:
      c
    max-item: 500000

# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity

