# ***************************通用配置: 请不要修改此文件，此文件由模板自动生成，若要修改，请移步至conftpl目录**************************** #
# 应用版本
version: 1.0.3.2
#Spring应用配置
spring:
  application.name: browser-sync
  #Redis集群配置
  redis:
    database: 0
    key:
      #区块列表
      blocks: browser:${version}:${profile}:blocks
      #交易列表
      transactions: browser:${version}:${profile}:transactions
      #统计信息
      networkStat: browser:${version}:${profile}:networkStat
      #代币交易
      innerTx: browser:${version}:${profile}:innerTx
    max-item: 500000