# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: prod
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://ctdb.cxkzgtponliu.ap-southeast-1.rds.amazonaws.com:3306/platon_aton_0.7.0?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(MnhyLpDl4QHrvI6j1ofu8g==)
    password: ENC(eqMAJvmLkdYCmZAdXS41WBnMG207Kg4/)
  #Redis配置
  redis:
    password: platscan
    ssl: true
    database: 0
    cluster:
      max-redirects: 3
      nodes: 192.168.16.171:7000,192.168.16.171:7001,192.168.16.171:7002,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: elastic
      password: changeme
# 内存环形缓冲区大小，必须是2的指数倍
disruptor:
  queue:
    # 区块事件环形缓冲区大小
    blockBufferSize: 1024
    # 采集事件环形缓冲区大小
    collectionBufferSize: 1024
    # 数据补充环形缓冲区大小
    complementBufferSize: 1024
    # gas price估算消息环形缓冲区大小
    gasEstimateBufferSize: 1024
    # 数据持久化环形缓冲区大小
    persistenceBufferSize: 1024
    #每次处理多少个
    persistenceBatchSize: 10
#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
#PlatOn相关配置
platon:
  # 地址HRP前缀
  addressPrefix: atp
  # 金额显示单位
  valueUnit: ATP
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.120.151:6789,192.168.120.151:6790
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/GalaxyRally/blob/master/PIPs/PIP-%s.md
  #proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 201018
  #Redis命名空间
  redis-namespace: browser:${version}:${profile}
  #Es索引命名空间
  es-namespace: browser_${version}_${profile}
  #同步时的索引查询分页参数配置
  paging:
    erc20-transaction:
      pageSize: 2000
      pageCount: 250
# v0.15.0.0版本新增功能涉及的配置
v0150:
  #锁仓最小释放金额参数生效版本
  restrictingMinimumReleaseActiveVersion: 3584
  #调账生效版本
  adjustmentActiveVersion: 3840
  #调账提案ID
  adjustmentPipId: '1609410836.4141252'
  #调账日志输出文件
  adjustLogFilePath: ./adjust.log

task:
  #地址统计任务批次大小
  addressBatchSize: 1000
  #agent与实际链上区块号相差多少个块号时触发调整操作
  gapForAdjust: 20
  #未追上链,批量入ES和Redis的缓存大小
  esRedisNotCatchupBatchSize: 10
  #已追上链,批量入ES和Redis的缓存大小
  esRedisCatchupBatchSize: 1