# ***************************通用配置: 请不要修改此文件，此文件由模板自动生成，若要修改，请移步至conftpl目录**************************** #
# 应用版本
version: 1.1.1.0
#Spring应用配置
spring:
  application.name: browser-export
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis集群配置
  redis:
    database: 0
    key:
      #区块列表
      blocks: browser:${version}:${profile}:blocks
      #交易列表
      transactions: browser:${version}:${profile}:transactions
      #统计信息
      networkStat: browser:${version}:${profile}:networkStat
      #代币交易
      innerTx: browser:${version}:${profile}:innerTx
    max-item: 500000
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity