# 指定环境
env: DEV
app:
  # 应用ID
  id: platon-scan-api
apollo:
  access-key:
    # 配置访问密钥
    secret: 2b61c16f7d2542eb965a470ba543a216
  bootstrap:
    # 是否开启 Apollo
    enabled: true
    eagerLoad:
      # 开启后，Apollo的配置会先于logback的配置加载
      enable: true
      # 指定使用哪个 Namespace 的配置，默认 application
    namespaces: application,platon
  # Apollo 配置中心地址，多个地址以逗号隔开
  # meta和env推荐使用VM参数指定 -Dapollo.configService=http://192.168.9.149:8080 -Denv=DEV
  # apollo.configService的优先级比apollo.meta高,configService会覆盖meta
  meta: http://10.0.0.34:8080
  # 配置本地配置缓存目录
  cacheDir: ./apolloCache/data/
  property:
    order:
      # 设置内存中的配置项是否保持和页面上的顺序一致
      enable: true