# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: dev
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#性能配置
server:
  port: 9061
  tomcat:
    max-connections: 20000
    threads:
      max: 2000
      min-spare: 800
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://_DB_HOST_:_DB_PORT_/alaya_browser_dev?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    # 使用p6spy监控SQL
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:p6spy:mysql://_DB_HOST_:_DB_PORT_/alaya_browser_0.15.2.0_hyp?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: _DB_USER_
    password: _DB_PASS_
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
  #Redis配置
  redis:
    password: _REDIS_PWD_
    cluster:
      max-redirects: 3
      nodes: _REDIS_IPS_
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: _ES_IPS_
      port: _ES_PORT_
      schema: http
      username: _ES_USER_
      password: _ES_PWD_
#日志配置
logging:
  #日志级别
  level:
    org.springframework: info
    com.platon.browser: info
    com.platon.browser.service: info
    com.platon.browser.task: info
    com.platon.browser.client: info
    com.platon.browser.dao: info
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %thread | trace-id[%X{trace-id}] | %logger{50} | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %thread | trace-id[%X{trace-id}] | %logger{50} | %msg%n"
#初始化链相关的配置
#初始化链相关的配置
platon:
  # 地址HRP前缀
  addressPrefix: atp
  # 金额显示单位
  valueUnit: ATP
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: WS
    addresses: 192.168.112.141:7789,192.168.112.141:7790
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 201600000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/tree/master/Alaya/PIP-%s.md
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 201018
  #Redis命名空间
  redis-namespace: browser:${profile}
  #Es索引命名空间
  es-namespace: browser_${profile}
  #0出块等待的循环访问时间(秒)
  zeroBlockNumber:
    wait-time: 60
recaptchaUrl: https://recaptcha.net/recaptcha/api/siteverify?secret=6Lf8KLcUAAAAAPyHZfa7oeWjdMSyvgDHUUeYf01Z&response=%s
limit:
  num: 10
output:
  file:
    url: /var/tmp